### ISSUE TITLE
Uncaught (in promise) DOMException

### ISSUE THREAD

**Issue by rampageservices** [larsgk/webusb-tester#1]
Hello,

I am testing an Allwinner R8 CPU in FEL mode. I came across your tester because I was getting Access Denied on my own code that used to work earlier this year. I'm using the latest version of Chrome Version 76.0.3809.100. I am getting an "Uncaught (in promise) DOMException" on line 85 where it returns in tryAttachDevice function.

Maybe both of our codebases need to be refactored to take advantage of the latest code changes to webusb?

**Comment by larsgk** [comment]
Hi, which device is it (e.g. `lsusb -vv` ) - and do you have a link to your codebase?

**Comment by rampageservices** [comment]
Hi @larsgk , Thanks for the prompt reply. I sorted out the problem on my end. I was missing a udev rule for the device. Once I added the rule and rebooted then your webusb-tester worked as expected.
It may be helpful for future testers to catch that error and output the Access Denied error. Thank you for writing this tool.
